theme: jekyll-theme-cayman
social:
  name: Milind Kejriwal
  links:
    - https://twitter.com/KejriwalMilind
    - https://www.linkedin.com/in/milind-kejriwal
    - https://github.com/Mkejriwal270
plugins:
  - jekyll-seo-tag
image: http://41.media.tumblr.com/173cb5c51a1c308ab022a786f69353f3/tumblr_nwncf1T2ht1rl195mo1_1280.jpg
defaults:
  - scope:
      path: ""
    values:
      image: http://41.media.tumblr.com/173cb5c51a1c308ab022a786f69353f3/tumblr_nwncf1T2ht1rl195mo1_1280.jpg
