theme: jekyll-theme-cayman
social:
  name: Milind Kejriwal
  links:
    - https://twitter.com/KejriwalMilind
    - https://www.linkedin.com/in/milind-kejriwal
    - https://github.com/Mkejriwal270
plugins:
  - jekyll-seo-tag
