theme: jekyll-theme-cayman
social:
  name: Milind Kejriwal
  links:
    - https://twitter.com/KejriwalMilind
    - https://www.linkedin.com/in/milind-kejriwal
    - https://github.com/Mkejriwal270
plugins:
  - jekyll-seo-tag
image: https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjJ8fHxlbnwwfHx8fA%3D%3D&w=1000&q=80
defaults:
  - scope:
      path: ""
    values:
      image: https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjJ8fHxlbnwwfHx8fA%3D%3D&w=1000&q=80
