{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "react-app.serviceAccountName" . }}
  labels:
    {{- include "react-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- with .Values.imagePullSecrets }}
secrets:
 {{- toYaml . | nindent 8 }}
{{- end }}