name: "Fire-It-Up"
on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'Enter cluster name'
        required: true
      subnets:
        description: 'Enter space-separated subnet values'     
        required: true
      vpc-id:
        description: 'Enter vpc ID'
        required: true
      angular_version:
        description: 'Enter app version for angular'
        required: true
      react_version:
        description: 'Enter app version for react'
        required: true
       
jobs:
   create_cluster:
      uses: Mkejriwal270/K8s-EKS-QuickStart/.github/workflows/Deploy-EKS-user-def-VPC.yaml@main
      with: 
        cluster_name: ${{ github.event.inputs.cluster_name }}
        subnets: ${{ github.event.inputs.subnets }}
        vpc-id: ${{ github.event.inputs.vpc-id }}
      secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        K8S_QS_TOKEN: ${{ secrets.K8S_QS_TOKEN }}
        
   setup_infra_components:
      uses: Mkejriwal270/K8s-EKS-QuickStart/.github/workflows/Update-Infra-Helm.yaml@main
      needs: create_cluster
      with:
        cluster_name: ${{ github.event.inputs.cluster_name }}
      secrets:  
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
   setup_angular_app:
      uses: Mkejriwal270/K8s-EKS-QuickStart/.github/workflows/Deploy-App.yaml@main
      needs: setup_infra_components
      with:
        cluster_name: ${{ github.event.inputs.cluster_name }}
        version: ${{ github.event.inputs.angular_name }}
        app_name: angular
      secrets:  
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
   setup_react_app:
      uses: Mkejriwal270/K8s-EKS-QuickStart/.github/workflows/Deploy-App.yaml@main
      needs: setup_infra_components
      with:
        app_name: react
        cluster_name: ${{ github.event.inputs.cluster_name }}
        version: ${{ github.event.inputs.react_version }}
      secrets:  
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
