name: "Update-Infra-Helm"
on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'Enter cluster name'
        required: true
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string

jobs:
  helm_install:
    name: "Helm_Install"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./charts/infra
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{github.event.inputs.cluster_name}}
        
      - name: Helm install ingress stack
        run: helm upgrade --install ingress-stack .
        working-directory: ./charts/infra/ingress-stack
      
      - name: Helm install app ingress
        run: helm upgrade --install ingress-app .
        working-directory: ./charts/infra/ingress-app
